"""Mock objects for external services."""
from typing import List


class MockOpenAIEmbeddingResponse:
    """Mock OpenAI embedding response."""
    
    def __init__(self, num_embeddings: int = 1):
        class MockData:
            def __init__(self):
                self.embedding = [0.1] * 1536
        
        self.data = [MockData() for _ in range(num_embeddings)]


class MockOpenAIChatResponse:
    """Mock OpenAI chat completion response."""
    
    class MockChoice:
        class MockMessage:
            content = "This is a test answer generated by the mock OpenAI client."
        message = MockMessage()
    
    class MockUsage:
        total_tokens = 150
        prompt_tokens = 100
        completion_tokens = 50
    
    choices = [MockChoice()]
    usage = MockUsage()


class MockChromaCollection:
    """Mock ChromaDB collection."""
    
    def __init__(self):
        self._data = []
        self._count = 0
    
    def count(self) -> int:
        return self._count
    
    def add(self, ids: List[str], embeddings: List[List[float]], documents: List[str], metadatas: List[dict]):
        """Mock add operation."""
        self._count += len(ids)
        self._data.append({
            'ids': ids,
            'embeddings': embeddings,
            'documents': documents,
            'metadatas': metadatas
        })
    
    def get(self, *args, **kwargs):
        """Mock get operation."""
        return {
            'ids': [],
            'documents': [],
            'metadatas': [],
            'embeddings': []
        }
    
    def query(self, query_embeddings: List[List[float]], n_results: int = 5, where: dict = None, *args, **kwargs):
        """Mock query operation."""
        return {
            'ids': [['test_chunk_1', 'test_chunk_2']],
            'documents': [['Test document chunk 1', 'Test document chunk 2']],
            'metadatas': [[
                {'ingestion_id': 'test_ingestion', 'device_id': 'test_device', 'position': 0},
                {'ingestion_id': 'test_ingestion', 'device_id': 'test_device', 'position': 1}
            ]],
            'distances': [[0.1, 0.2]]
        }
